-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- create table pca_query_virt_voc_sensors(sensor_id int, ts timestamp with time zone, voc real);
