# @warn ONLY EDIT this file from the airmap repository (not deployment systems)
services:
  pca_db:
    # The std pg14 image crashes with SSL options on boot only. issue filed with timescale
    image: timescale/timescaledb-ha:pg14
    volumes:
      - $PWD/.docker/db:/var/lib/postgresql/data
  pca_gql:
    ports:
      - 8080:8080
    volumes:
      - $PWD/.docker/hasura:/pca
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://airman:${PCA_DB_PASSWORD}@pca_db:5544/pca
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${PCA_GQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log
      #, query-log
      HASURA_GRAPHQL_METADATA_DIRECTORY: /pca/metadata
      HASURA_GRAPHQL_MIGRATIONS_DIRECTORY: /pca/migrations
      HASURA_GRAPHQL_SEEDS_DIRECTORY: /pca/seeds
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: readonly
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE: 10
      HASURA_GRAPHQL_SCHEMA_SYNC_POLL_INTERVAL: 60000
