-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."observation_purpleair" add column "sensor_id" varchar
--  not null;
